# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/Yingchen/Documents/GitHub/midifile

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/Yingchen/Documents/GitHub/midifile

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Yingchen/Documents/GitHub/midifile/CMakeFiles /mnt/c/Users/Yingchen/Documents/GitHub/midifile/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Yingchen/Documents/GitHub/midifile/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named midi2text

# Build rule for target.
midi2text: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 midi2text
.PHONY : midi2text

# fast build rule for target.
midi2text/fast:
	$(MAKE) -f CMakeFiles/midi2text.dir/build.make CMakeFiles/midi2text.dir/build
.PHONY : midi2text/fast

#=============================================================================
# Target rules for targets named midi2notes

# Build rule for target.
midi2notes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 midi2notes
.PHONY : midi2notes

# fast build rule for target.
midi2notes/fast:
	$(MAKE) -f CMakeFiles/midi2notes.dir/build.make CMakeFiles/midi2notes.dir/build
.PHONY : midi2notes/fast

#=============================================================================
# Target rules for targets named midifile

# Build rule for target.
midifile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 midifile
.PHONY : midifile

# fast build rule for target.
midifile/fast:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/build
.PHONY : midifile/fast

#=============================================================================
# Target rules for targets named tobinary

# Build rule for target.
tobinary: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tobinary
.PHONY : tobinary

# fast build rule for target.
tobinary/fast:
	$(MAKE) -f CMakeFiles/tobinary.dir/build.make CMakeFiles/tobinary.dir/build
.PHONY : tobinary/fast

#=============================================================================
# Target rules for targets named tohex

# Build rule for target.
tohex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tohex
.PHONY : tohex

# fast build rule for target.
tohex/fast:
	$(MAKE) -f CMakeFiles/tohex.dir/build.make CMakeFiles/tohex.dir/build
.PHONY : tohex/fast

#=============================================================================
# Target rules for targets named midi2melody

# Build rule for target.
midi2melody: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 midi2melody
.PHONY : midi2melody

# fast build rule for target.
midi2melody/fast:
	$(MAKE) -f CMakeFiles/midi2melody.dir/build.make CMakeFiles/midi2melody.dir/build
.PHONY : midi2melody/fast

#=============================================================================
# Target rules for targets named midi2binasc

# Build rule for target.
midi2binasc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 midi2binasc
.PHONY : midi2binasc

# fast build rule for target.
midi2binasc/fast:
	$(MAKE) -f CMakeFiles/midi2binasc.dir/build.make CMakeFiles/midi2binasc.dir/build
.PHONY : midi2binasc/fast

#=============================================================================
# Target rules for targets named mid2mat

# Build rule for target.
mid2mat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mid2mat
.PHONY : mid2mat

# fast build rule for target.
mid2mat/fast:
	$(MAKE) -f CMakeFiles/mid2mat.dir/build.make CMakeFiles/mid2mat.dir/build
.PHONY : mid2mat/fast

#=============================================================================
# Target rules for targets named retick

# Build rule for target.
retick: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 retick
.PHONY : retick

# fast build rule for target.
retick/fast:
	$(MAKE) -f CMakeFiles/retick.dir/build.make CMakeFiles/retick.dir/build
.PHONY : retick/fast

#=============================================================================
# Target rules for targets named durations

# Build rule for target.
durations: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 durations
.PHONY : durations

# fast build rule for target.
durations/fast:
	$(MAKE) -f CMakeFiles/durations.dir/build.make CMakeFiles/durations.dir/build
.PHONY : durations/fast

#=============================================================================
# Target rules for targets named createmidifile2

# Build rule for target.
createmidifile2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 createmidifile2
.PHONY : createmidifile2

# fast build rule for target.
createmidifile2/fast:
	$(MAKE) -f CMakeFiles/createmidifile2.dir/build.make CMakeFiles/createmidifile2.dir/build
.PHONY : createmidifile2/fast

#=============================================================================
# Target rules for targets named textmidi

# Build rule for target.
textmidi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 textmidi
.PHONY : textmidi

# fast build rule for target.
textmidi/fast:
	$(MAKE) -f CMakeFiles/textmidi.dir/build.make CMakeFiles/textmidi.dir/build
.PHONY : textmidi/fast

#=============================================================================
# Target rules for targets named mid2svg

# Build rule for target.
mid2svg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mid2svg
.PHONY : mid2svg

# fast build rule for target.
mid2svg/fast:
	$(MAKE) -f CMakeFiles/mid2svg.dir/build.make CMakeFiles/mid2svg.dir/build
.PHONY : mid2svg/fast

#=============================================================================
# Target rules for targets named mid2mtb

# Build rule for target.
mid2mtb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mid2mtb
.PHONY : mid2mtb

# fast build rule for target.
mid2mtb/fast:
	$(MAKE) -f CMakeFiles/mid2mtb.dir/build.make CMakeFiles/mid2mtb.dir/build
.PHONY : mid2mtb/fast

#=============================================================================
# Target rules for targets named midi2skini

# Build rule for target.
midi2skini: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 midi2skini
.PHONY : midi2skini

# fast build rule for target.
midi2skini/fast:
	$(MAKE) -f CMakeFiles/midi2skini.dir/build.make CMakeFiles/midi2skini.dir/build
.PHONY : midi2skini/fast

#=============================================================================
# Target rules for targets named drumtab

# Build rule for target.
drumtab: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drumtab
.PHONY : drumtab

# fast build rule for target.
drumtab/fast:
	$(MAKE) -f CMakeFiles/drumtab.dir/build.make CMakeFiles/drumtab.dir/build
.PHONY : drumtab/fast

#=============================================================================
# Target rules for targets named asciimidi

# Build rule for target.
asciimidi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 asciimidi
.PHONY : asciimidi

# fast build rule for target.
asciimidi/fast:
	$(MAKE) -f CMakeFiles/asciimidi.dir/build.make CMakeFiles/asciimidi.dir/build
.PHONY : asciimidi/fast

#=============================================================================
# Target rules for targets named binasc

# Build rule for target.
binasc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 binasc
.PHONY : binasc

# fast build rule for target.
binasc/fast:
	$(MAKE) -f CMakeFiles/binasc.dir/build.make CMakeFiles/binasc.dir/build
.PHONY : binasc/fast

#=============================================================================
# Target rules for targets named createmidifile

# Build rule for target.
createmidifile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 createmidifile
.PHONY : createmidifile

# fast build rule for target.
createmidifile/fast:
	$(MAKE) -f CMakeFiles/createmidifile.dir/build.make CMakeFiles/createmidifile.dir/build
.PHONY : createmidifile/fast

#=============================================================================
# Target rules for targets named midicat

# Build rule for target.
midicat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 midicat
.PHONY : midicat

# fast build rule for target.
midicat/fast:
	$(MAKE) -f CMakeFiles/midicat.dir/build.make CMakeFiles/midicat.dir/build
.PHONY : midicat/fast

#=============================================================================
# Target rules for targets named fyp

# Build rule for target.
fyp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fyp
.PHONY : fyp

# fast build rule for target.
fyp/fast:
	$(MAKE) -f CMakeFiles/fyp.dir/build.make CMakeFiles/fyp.dir/build
.PHONY : fyp/fast

#=============================================================================
# Target rules for targets named midimixup

# Build rule for target.
midimixup: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 midimixup
.PHONY : midimixup

# fast build rule for target.
midimixup/fast:
	$(MAKE) -f CMakeFiles/midimixup.dir/build.make CMakeFiles/midimixup.dir/build
.PHONY : midimixup/fast

#=============================================================================
# Target rules for targets named miditime

# Build rule for target.
miditime: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 miditime
.PHONY : miditime

# fast build rule for target.
miditime/fast:
	$(MAKE) -f CMakeFiles/miditime.dir/build.make CMakeFiles/miditime.dir/build
.PHONY : miditime/fast

#=============================================================================
# Target rules for targets named sysextest

# Build rule for target.
sysextest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sysextest
.PHONY : sysextest

# fast build rule for target.
sysextest/fast:
	$(MAKE) -f CMakeFiles/sysextest.dir/build.make CMakeFiles/sysextest.dir/build
.PHONY : sysextest/fast

#=============================================================================
# Target rules for targets named todec

# Build rule for target.
todec: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 todec
.PHONY : todec

# fast build rule for target.
todec/fast:
	$(MAKE) -f CMakeFiles/todec.dir/build.make CMakeFiles/todec.dir/build
.PHONY : todec/fast

#=============================================================================
# Target rules for targets named midi2beep

# Build rule for target.
midi2beep: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 midi2beep
.PHONY : midi2beep

# fast build rule for target.
midi2beep/fast:
	$(MAKE) -f CMakeFiles/midi2beep.dir/build.make CMakeFiles/midi2beep.dir/build
.PHONY : midi2beep/fast

#=============================================================================
# Target rules for targets named perfid

# Build rule for target.
perfid: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 perfid
.PHONY : perfid

# fast build rule for target.
perfid/fast:
	$(MAKE) -f CMakeFiles/perfid.dir/build.make CMakeFiles/perfid.dir/build
.PHONY : perfid/fast

#=============================================================================
# Target rules for targets named toascii

# Build rule for target.
toascii: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 toascii
.PHONY : toascii

# fast build rule for target.
toascii/fast:
	$(MAKE) -f CMakeFiles/toascii.dir/build.make CMakeFiles/toascii.dir/build
.PHONY : toascii/fast

#=============================================================================
# Target rules for targets named type0

# Build rule for target.
type0: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 type0
.PHONY : type0

# fast build rule for target.
type0/fast:
	$(MAKE) -f CMakeFiles/type0.dir/build.make CMakeFiles/type0.dir/build
.PHONY : type0/fast

#=============================================================================
# Target rules for targets named shutak

# Build rule for target.
shutak: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shutak
.PHONY : shutak

# fast build rule for target.
shutak/fast:
	$(MAKE) -f CMakeFiles/shutak.dir/build.make CMakeFiles/shutak.dir/build
.PHONY : shutak/fast

#=============================================================================
# Target rules for targets named 80off

# Build rule for target.
80off: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 80off
.PHONY : 80off

# fast build rule for target.
80off/fast:
	$(MAKE) -f CMakeFiles/80off.dir/build.make CMakeFiles/80off.dir/build
.PHONY : 80off/fast

#=============================================================================
# Target rules for targets named text2midi

# Build rule for target.
text2midi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 text2midi
.PHONY : text2midi

# fast build rule for target.
text2midi/fast:
	$(MAKE) -f CMakeFiles/text2midi.dir/build.make CMakeFiles/text2midi.dir/build
.PHONY : text2midi/fast

#=============================================================================
# Target rules for targets named smfdur

# Build rule for target.
smfdur: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smfdur
.PHONY : smfdur

# fast build rule for target.
smfdur/fast:
	$(MAKE) -f CMakeFiles/smfdur.dir/build.make CMakeFiles/smfdur.dir/build
.PHONY : smfdur/fast

#=============================================================================
# Target rules for targets named stretch

# Build rule for target.
stretch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stretch
.PHONY : stretch

# fast build rule for target.
stretch/fast:
	$(MAKE) -f CMakeFiles/stretch.dir/build.make CMakeFiles/stretch.dir/build
.PHONY : stretch/fast

#=============================================================================
# Target rules for targets named tobin

# Build rule for target.
tobin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tobin
.PHONY : tobin

# fast build rule for target.
tobin/fast:
	$(MAKE) -f CMakeFiles/tobin.dir/build.make CMakeFiles/tobin.dir/build
.PHONY : tobin/fast

#=============================================================================
# Target rules for targets named vlv

# Build rule for target.
vlv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vlv
.PHONY : vlv

# fast build rule for target.
vlv/fast:
	$(MAKE) -f CMakeFiles/vlv.dir/build.make CMakeFiles/vlv.dir/build
.PHONY : vlv/fast

src-library/Binasc.o: src-library/Binasc.cpp.o

.PHONY : src-library/Binasc.o

# target to build an object file
src-library/Binasc.cpp.o:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/src-library/Binasc.cpp.o
.PHONY : src-library/Binasc.cpp.o

src-library/Binasc.i: src-library/Binasc.cpp.i

.PHONY : src-library/Binasc.i

# target to preprocess a source file
src-library/Binasc.cpp.i:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/src-library/Binasc.cpp.i
.PHONY : src-library/Binasc.cpp.i

src-library/Binasc.s: src-library/Binasc.cpp.s

.PHONY : src-library/Binasc.s

# target to generate assembly for a file
src-library/Binasc.cpp.s:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/src-library/Binasc.cpp.s
.PHONY : src-library/Binasc.cpp.s

src-library/MidiCat.o: src-library/MidiCat.cpp.o

.PHONY : src-library/MidiCat.o

# target to build an object file
src-library/MidiCat.cpp.o:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/src-library/MidiCat.cpp.o
.PHONY : src-library/MidiCat.cpp.o

src-library/MidiCat.i: src-library/MidiCat.cpp.i

.PHONY : src-library/MidiCat.i

# target to preprocess a source file
src-library/MidiCat.cpp.i:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/src-library/MidiCat.cpp.i
.PHONY : src-library/MidiCat.cpp.i

src-library/MidiCat.s: src-library/MidiCat.cpp.s

.PHONY : src-library/MidiCat.s

# target to generate assembly for a file
src-library/MidiCat.cpp.s:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/src-library/MidiCat.cpp.s
.PHONY : src-library/MidiCat.cpp.s

src-library/MidiEvent.o: src-library/MidiEvent.cpp.o

.PHONY : src-library/MidiEvent.o

# target to build an object file
src-library/MidiEvent.cpp.o:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/src-library/MidiEvent.cpp.o
.PHONY : src-library/MidiEvent.cpp.o

src-library/MidiEvent.i: src-library/MidiEvent.cpp.i

.PHONY : src-library/MidiEvent.i

# target to preprocess a source file
src-library/MidiEvent.cpp.i:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/src-library/MidiEvent.cpp.i
.PHONY : src-library/MidiEvent.cpp.i

src-library/MidiEvent.s: src-library/MidiEvent.cpp.s

.PHONY : src-library/MidiEvent.s

# target to generate assembly for a file
src-library/MidiEvent.cpp.s:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/src-library/MidiEvent.cpp.s
.PHONY : src-library/MidiEvent.cpp.s

src-library/MidiEventList.o: src-library/MidiEventList.cpp.o

.PHONY : src-library/MidiEventList.o

# target to build an object file
src-library/MidiEventList.cpp.o:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/src-library/MidiEventList.cpp.o
.PHONY : src-library/MidiEventList.cpp.o

src-library/MidiEventList.i: src-library/MidiEventList.cpp.i

.PHONY : src-library/MidiEventList.i

# target to preprocess a source file
src-library/MidiEventList.cpp.i:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/src-library/MidiEventList.cpp.i
.PHONY : src-library/MidiEventList.cpp.i

src-library/MidiEventList.s: src-library/MidiEventList.cpp.s

.PHONY : src-library/MidiEventList.s

# target to generate assembly for a file
src-library/MidiEventList.cpp.s:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/src-library/MidiEventList.cpp.s
.PHONY : src-library/MidiEventList.cpp.s

src-library/MidiExcerptByBar.o: src-library/MidiExcerptByBar.cpp.o

.PHONY : src-library/MidiExcerptByBar.o

# target to build an object file
src-library/MidiExcerptByBar.cpp.o:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/src-library/MidiExcerptByBar.cpp.o
.PHONY : src-library/MidiExcerptByBar.cpp.o

src-library/MidiExcerptByBar.i: src-library/MidiExcerptByBar.cpp.i

.PHONY : src-library/MidiExcerptByBar.i

# target to preprocess a source file
src-library/MidiExcerptByBar.cpp.i:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/src-library/MidiExcerptByBar.cpp.i
.PHONY : src-library/MidiExcerptByBar.cpp.i

src-library/MidiExcerptByBar.s: src-library/MidiExcerptByBar.cpp.s

.PHONY : src-library/MidiExcerptByBar.s

# target to generate assembly for a file
src-library/MidiExcerptByBar.cpp.s:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/src-library/MidiExcerptByBar.cpp.s
.PHONY : src-library/MidiExcerptByBar.cpp.s

src-library/MidiFile.o: src-library/MidiFile.cpp.o

.PHONY : src-library/MidiFile.o

# target to build an object file
src-library/MidiFile.cpp.o:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/src-library/MidiFile.cpp.o
.PHONY : src-library/MidiFile.cpp.o

src-library/MidiFile.i: src-library/MidiFile.cpp.i

.PHONY : src-library/MidiFile.i

# target to preprocess a source file
src-library/MidiFile.cpp.i:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/src-library/MidiFile.cpp.i
.PHONY : src-library/MidiFile.cpp.i

src-library/MidiFile.s: src-library/MidiFile.cpp.s

.PHONY : src-library/MidiFile.s

# target to generate assembly for a file
src-library/MidiFile.cpp.s:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/src-library/MidiFile.cpp.s
.PHONY : src-library/MidiFile.cpp.s

src-library/MidiMessage.o: src-library/MidiMessage.cpp.o

.PHONY : src-library/MidiMessage.o

# target to build an object file
src-library/MidiMessage.cpp.o:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/src-library/MidiMessage.cpp.o
.PHONY : src-library/MidiMessage.cpp.o

src-library/MidiMessage.i: src-library/MidiMessage.cpp.i

.PHONY : src-library/MidiMessage.i

# target to preprocess a source file
src-library/MidiMessage.cpp.i:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/src-library/MidiMessage.cpp.i
.PHONY : src-library/MidiMessage.cpp.i

src-library/MidiMessage.s: src-library/MidiMessage.cpp.s

.PHONY : src-library/MidiMessage.s

# target to generate assembly for a file
src-library/MidiMessage.cpp.s:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/src-library/MidiMessage.cpp.s
.PHONY : src-library/MidiMessage.cpp.s

src-library/MusicSegment.o: src-library/MusicSegment.cpp.o

.PHONY : src-library/MusicSegment.o

# target to build an object file
src-library/MusicSegment.cpp.o:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/src-library/MusicSegment.cpp.o
.PHONY : src-library/MusicSegment.cpp.o

src-library/MusicSegment.i: src-library/MusicSegment.cpp.i

.PHONY : src-library/MusicSegment.i

# target to preprocess a source file
src-library/MusicSegment.cpp.i:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/src-library/MusicSegment.cpp.i
.PHONY : src-library/MusicSegment.cpp.i

src-library/MusicSegment.s: src-library/MusicSegment.cpp.s

.PHONY : src-library/MusicSegment.s

# target to generate assembly for a file
src-library/MusicSegment.cpp.s:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/src-library/MusicSegment.cpp.s
.PHONY : src-library/MusicSegment.cpp.s

src-library/Options.o: src-library/Options.cpp.o

.PHONY : src-library/Options.o

# target to build an object file
src-library/Options.cpp.o:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/src-library/Options.cpp.o
.PHONY : src-library/Options.cpp.o

src-library/Options.i: src-library/Options.cpp.i

.PHONY : src-library/Options.i

# target to preprocess a source file
src-library/Options.cpp.i:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/src-library/Options.cpp.i
.PHONY : src-library/Options.cpp.i

src-library/Options.s: src-library/Options.cpp.s

.PHONY : src-library/Options.s

# target to generate assembly for a file
src-library/Options.cpp.s:
	$(MAKE) -f CMakeFiles/midifile.dir/build.make CMakeFiles/midifile.dir/src-library/Options.cpp.s
.PHONY : src-library/Options.cpp.s

src-programs/80off.o: src-programs/80off.cpp.o

.PHONY : src-programs/80off.o

# target to build an object file
src-programs/80off.cpp.o:
	$(MAKE) -f CMakeFiles/80off.dir/build.make CMakeFiles/80off.dir/src-programs/80off.cpp.o
.PHONY : src-programs/80off.cpp.o

src-programs/80off.i: src-programs/80off.cpp.i

.PHONY : src-programs/80off.i

# target to preprocess a source file
src-programs/80off.cpp.i:
	$(MAKE) -f CMakeFiles/80off.dir/build.make CMakeFiles/80off.dir/src-programs/80off.cpp.i
.PHONY : src-programs/80off.cpp.i

src-programs/80off.s: src-programs/80off.cpp.s

.PHONY : src-programs/80off.s

# target to generate assembly for a file
src-programs/80off.cpp.s:
	$(MAKE) -f CMakeFiles/80off.dir/build.make CMakeFiles/80off.dir/src-programs/80off.cpp.s
.PHONY : src-programs/80off.cpp.s

src-programs/asciimidi.o: src-programs/asciimidi.cpp.o

.PHONY : src-programs/asciimidi.o

# target to build an object file
src-programs/asciimidi.cpp.o:
	$(MAKE) -f CMakeFiles/asciimidi.dir/build.make CMakeFiles/asciimidi.dir/src-programs/asciimidi.cpp.o
.PHONY : src-programs/asciimidi.cpp.o

src-programs/asciimidi.i: src-programs/asciimidi.cpp.i

.PHONY : src-programs/asciimidi.i

# target to preprocess a source file
src-programs/asciimidi.cpp.i:
	$(MAKE) -f CMakeFiles/asciimidi.dir/build.make CMakeFiles/asciimidi.dir/src-programs/asciimidi.cpp.i
.PHONY : src-programs/asciimidi.cpp.i

src-programs/asciimidi.s: src-programs/asciimidi.cpp.s

.PHONY : src-programs/asciimidi.s

# target to generate assembly for a file
src-programs/asciimidi.cpp.s:
	$(MAKE) -f CMakeFiles/asciimidi.dir/build.make CMakeFiles/asciimidi.dir/src-programs/asciimidi.cpp.s
.PHONY : src-programs/asciimidi.cpp.s

src-programs/binasc.o: src-programs/binasc.cpp.o

.PHONY : src-programs/binasc.o

# target to build an object file
src-programs/binasc.cpp.o:
	$(MAKE) -f CMakeFiles/binasc.dir/build.make CMakeFiles/binasc.dir/src-programs/binasc.cpp.o
.PHONY : src-programs/binasc.cpp.o

src-programs/binasc.i: src-programs/binasc.cpp.i

.PHONY : src-programs/binasc.i

# target to preprocess a source file
src-programs/binasc.cpp.i:
	$(MAKE) -f CMakeFiles/binasc.dir/build.make CMakeFiles/binasc.dir/src-programs/binasc.cpp.i
.PHONY : src-programs/binasc.cpp.i

src-programs/binasc.s: src-programs/binasc.cpp.s

.PHONY : src-programs/binasc.s

# target to generate assembly for a file
src-programs/binasc.cpp.s:
	$(MAKE) -f CMakeFiles/binasc.dir/build.make CMakeFiles/binasc.dir/src-programs/binasc.cpp.s
.PHONY : src-programs/binasc.cpp.s

src-programs/createmidifile.o: src-programs/createmidifile.cpp.o

.PHONY : src-programs/createmidifile.o

# target to build an object file
src-programs/createmidifile.cpp.o:
	$(MAKE) -f CMakeFiles/createmidifile.dir/build.make CMakeFiles/createmidifile.dir/src-programs/createmidifile.cpp.o
.PHONY : src-programs/createmidifile.cpp.o

src-programs/createmidifile.i: src-programs/createmidifile.cpp.i

.PHONY : src-programs/createmidifile.i

# target to preprocess a source file
src-programs/createmidifile.cpp.i:
	$(MAKE) -f CMakeFiles/createmidifile.dir/build.make CMakeFiles/createmidifile.dir/src-programs/createmidifile.cpp.i
.PHONY : src-programs/createmidifile.cpp.i

src-programs/createmidifile.s: src-programs/createmidifile.cpp.s

.PHONY : src-programs/createmidifile.s

# target to generate assembly for a file
src-programs/createmidifile.cpp.s:
	$(MAKE) -f CMakeFiles/createmidifile.dir/build.make CMakeFiles/createmidifile.dir/src-programs/createmidifile.cpp.s
.PHONY : src-programs/createmidifile.cpp.s

src-programs/createmidifile2.o: src-programs/createmidifile2.cpp.o

.PHONY : src-programs/createmidifile2.o

# target to build an object file
src-programs/createmidifile2.cpp.o:
	$(MAKE) -f CMakeFiles/createmidifile2.dir/build.make CMakeFiles/createmidifile2.dir/src-programs/createmidifile2.cpp.o
.PHONY : src-programs/createmidifile2.cpp.o

src-programs/createmidifile2.i: src-programs/createmidifile2.cpp.i

.PHONY : src-programs/createmidifile2.i

# target to preprocess a source file
src-programs/createmidifile2.cpp.i:
	$(MAKE) -f CMakeFiles/createmidifile2.dir/build.make CMakeFiles/createmidifile2.dir/src-programs/createmidifile2.cpp.i
.PHONY : src-programs/createmidifile2.cpp.i

src-programs/createmidifile2.s: src-programs/createmidifile2.cpp.s

.PHONY : src-programs/createmidifile2.s

# target to generate assembly for a file
src-programs/createmidifile2.cpp.s:
	$(MAKE) -f CMakeFiles/createmidifile2.dir/build.make CMakeFiles/createmidifile2.dir/src-programs/createmidifile2.cpp.s
.PHONY : src-programs/createmidifile2.cpp.s

src-programs/drumtab.o: src-programs/drumtab.cpp.o

.PHONY : src-programs/drumtab.o

# target to build an object file
src-programs/drumtab.cpp.o:
	$(MAKE) -f CMakeFiles/drumtab.dir/build.make CMakeFiles/drumtab.dir/src-programs/drumtab.cpp.o
.PHONY : src-programs/drumtab.cpp.o

src-programs/drumtab.i: src-programs/drumtab.cpp.i

.PHONY : src-programs/drumtab.i

# target to preprocess a source file
src-programs/drumtab.cpp.i:
	$(MAKE) -f CMakeFiles/drumtab.dir/build.make CMakeFiles/drumtab.dir/src-programs/drumtab.cpp.i
.PHONY : src-programs/drumtab.cpp.i

src-programs/drumtab.s: src-programs/drumtab.cpp.s

.PHONY : src-programs/drumtab.s

# target to generate assembly for a file
src-programs/drumtab.cpp.s:
	$(MAKE) -f CMakeFiles/drumtab.dir/build.make CMakeFiles/drumtab.dir/src-programs/drumtab.cpp.s
.PHONY : src-programs/drumtab.cpp.s

src-programs/durations.o: src-programs/durations.cpp.o

.PHONY : src-programs/durations.o

# target to build an object file
src-programs/durations.cpp.o:
	$(MAKE) -f CMakeFiles/durations.dir/build.make CMakeFiles/durations.dir/src-programs/durations.cpp.o
.PHONY : src-programs/durations.cpp.o

src-programs/durations.i: src-programs/durations.cpp.i

.PHONY : src-programs/durations.i

# target to preprocess a source file
src-programs/durations.cpp.i:
	$(MAKE) -f CMakeFiles/durations.dir/build.make CMakeFiles/durations.dir/src-programs/durations.cpp.i
.PHONY : src-programs/durations.cpp.i

src-programs/durations.s: src-programs/durations.cpp.s

.PHONY : src-programs/durations.s

# target to generate assembly for a file
src-programs/durations.cpp.s:
	$(MAKE) -f CMakeFiles/durations.dir/build.make CMakeFiles/durations.dir/src-programs/durations.cpp.s
.PHONY : src-programs/durations.cpp.s

src-programs/fyp.o: src-programs/fyp.cpp.o

.PHONY : src-programs/fyp.o

# target to build an object file
src-programs/fyp.cpp.o:
	$(MAKE) -f CMakeFiles/fyp.dir/build.make CMakeFiles/fyp.dir/src-programs/fyp.cpp.o
.PHONY : src-programs/fyp.cpp.o

src-programs/fyp.i: src-programs/fyp.cpp.i

.PHONY : src-programs/fyp.i

# target to preprocess a source file
src-programs/fyp.cpp.i:
	$(MAKE) -f CMakeFiles/fyp.dir/build.make CMakeFiles/fyp.dir/src-programs/fyp.cpp.i
.PHONY : src-programs/fyp.cpp.i

src-programs/fyp.s: src-programs/fyp.cpp.s

.PHONY : src-programs/fyp.s

# target to generate assembly for a file
src-programs/fyp.cpp.s:
	$(MAKE) -f CMakeFiles/fyp.dir/build.make CMakeFiles/fyp.dir/src-programs/fyp.cpp.s
.PHONY : src-programs/fyp.cpp.s

src-programs/mid2mat.o: src-programs/mid2mat.cpp.o

.PHONY : src-programs/mid2mat.o

# target to build an object file
src-programs/mid2mat.cpp.o:
	$(MAKE) -f CMakeFiles/mid2mat.dir/build.make CMakeFiles/mid2mat.dir/src-programs/mid2mat.cpp.o
.PHONY : src-programs/mid2mat.cpp.o

src-programs/mid2mat.i: src-programs/mid2mat.cpp.i

.PHONY : src-programs/mid2mat.i

# target to preprocess a source file
src-programs/mid2mat.cpp.i:
	$(MAKE) -f CMakeFiles/mid2mat.dir/build.make CMakeFiles/mid2mat.dir/src-programs/mid2mat.cpp.i
.PHONY : src-programs/mid2mat.cpp.i

src-programs/mid2mat.s: src-programs/mid2mat.cpp.s

.PHONY : src-programs/mid2mat.s

# target to generate assembly for a file
src-programs/mid2mat.cpp.s:
	$(MAKE) -f CMakeFiles/mid2mat.dir/build.make CMakeFiles/mid2mat.dir/src-programs/mid2mat.cpp.s
.PHONY : src-programs/mid2mat.cpp.s

src-programs/mid2mtb.o: src-programs/mid2mtb.cpp.o

.PHONY : src-programs/mid2mtb.o

# target to build an object file
src-programs/mid2mtb.cpp.o:
	$(MAKE) -f CMakeFiles/mid2mtb.dir/build.make CMakeFiles/mid2mtb.dir/src-programs/mid2mtb.cpp.o
.PHONY : src-programs/mid2mtb.cpp.o

src-programs/mid2mtb.i: src-programs/mid2mtb.cpp.i

.PHONY : src-programs/mid2mtb.i

# target to preprocess a source file
src-programs/mid2mtb.cpp.i:
	$(MAKE) -f CMakeFiles/mid2mtb.dir/build.make CMakeFiles/mid2mtb.dir/src-programs/mid2mtb.cpp.i
.PHONY : src-programs/mid2mtb.cpp.i

src-programs/mid2mtb.s: src-programs/mid2mtb.cpp.s

.PHONY : src-programs/mid2mtb.s

# target to generate assembly for a file
src-programs/mid2mtb.cpp.s:
	$(MAKE) -f CMakeFiles/mid2mtb.dir/build.make CMakeFiles/mid2mtb.dir/src-programs/mid2mtb.cpp.s
.PHONY : src-programs/mid2mtb.cpp.s

src-programs/mid2svg.o: src-programs/mid2svg.cpp.o

.PHONY : src-programs/mid2svg.o

# target to build an object file
src-programs/mid2svg.cpp.o:
	$(MAKE) -f CMakeFiles/mid2svg.dir/build.make CMakeFiles/mid2svg.dir/src-programs/mid2svg.cpp.o
.PHONY : src-programs/mid2svg.cpp.o

src-programs/mid2svg.i: src-programs/mid2svg.cpp.i

.PHONY : src-programs/mid2svg.i

# target to preprocess a source file
src-programs/mid2svg.cpp.i:
	$(MAKE) -f CMakeFiles/mid2svg.dir/build.make CMakeFiles/mid2svg.dir/src-programs/mid2svg.cpp.i
.PHONY : src-programs/mid2svg.cpp.i

src-programs/mid2svg.s: src-programs/mid2svg.cpp.s

.PHONY : src-programs/mid2svg.s

# target to generate assembly for a file
src-programs/mid2svg.cpp.s:
	$(MAKE) -f CMakeFiles/mid2svg.dir/build.make CMakeFiles/mid2svg.dir/src-programs/mid2svg.cpp.s
.PHONY : src-programs/mid2svg.cpp.s

src-programs/midi2beep.o: src-programs/midi2beep.cpp.o

.PHONY : src-programs/midi2beep.o

# target to build an object file
src-programs/midi2beep.cpp.o:
	$(MAKE) -f CMakeFiles/midi2beep.dir/build.make CMakeFiles/midi2beep.dir/src-programs/midi2beep.cpp.o
.PHONY : src-programs/midi2beep.cpp.o

src-programs/midi2beep.i: src-programs/midi2beep.cpp.i

.PHONY : src-programs/midi2beep.i

# target to preprocess a source file
src-programs/midi2beep.cpp.i:
	$(MAKE) -f CMakeFiles/midi2beep.dir/build.make CMakeFiles/midi2beep.dir/src-programs/midi2beep.cpp.i
.PHONY : src-programs/midi2beep.cpp.i

src-programs/midi2beep.s: src-programs/midi2beep.cpp.s

.PHONY : src-programs/midi2beep.s

# target to generate assembly for a file
src-programs/midi2beep.cpp.s:
	$(MAKE) -f CMakeFiles/midi2beep.dir/build.make CMakeFiles/midi2beep.dir/src-programs/midi2beep.cpp.s
.PHONY : src-programs/midi2beep.cpp.s

src-programs/midi2binasc.o: src-programs/midi2binasc.cpp.o

.PHONY : src-programs/midi2binasc.o

# target to build an object file
src-programs/midi2binasc.cpp.o:
	$(MAKE) -f CMakeFiles/midi2binasc.dir/build.make CMakeFiles/midi2binasc.dir/src-programs/midi2binasc.cpp.o
.PHONY : src-programs/midi2binasc.cpp.o

src-programs/midi2binasc.i: src-programs/midi2binasc.cpp.i

.PHONY : src-programs/midi2binasc.i

# target to preprocess a source file
src-programs/midi2binasc.cpp.i:
	$(MAKE) -f CMakeFiles/midi2binasc.dir/build.make CMakeFiles/midi2binasc.dir/src-programs/midi2binasc.cpp.i
.PHONY : src-programs/midi2binasc.cpp.i

src-programs/midi2binasc.s: src-programs/midi2binasc.cpp.s

.PHONY : src-programs/midi2binasc.s

# target to generate assembly for a file
src-programs/midi2binasc.cpp.s:
	$(MAKE) -f CMakeFiles/midi2binasc.dir/build.make CMakeFiles/midi2binasc.dir/src-programs/midi2binasc.cpp.s
.PHONY : src-programs/midi2binasc.cpp.s

src-programs/midi2melody.o: src-programs/midi2melody.cpp.o

.PHONY : src-programs/midi2melody.o

# target to build an object file
src-programs/midi2melody.cpp.o:
	$(MAKE) -f CMakeFiles/midi2melody.dir/build.make CMakeFiles/midi2melody.dir/src-programs/midi2melody.cpp.o
.PHONY : src-programs/midi2melody.cpp.o

src-programs/midi2melody.i: src-programs/midi2melody.cpp.i

.PHONY : src-programs/midi2melody.i

# target to preprocess a source file
src-programs/midi2melody.cpp.i:
	$(MAKE) -f CMakeFiles/midi2melody.dir/build.make CMakeFiles/midi2melody.dir/src-programs/midi2melody.cpp.i
.PHONY : src-programs/midi2melody.cpp.i

src-programs/midi2melody.s: src-programs/midi2melody.cpp.s

.PHONY : src-programs/midi2melody.s

# target to generate assembly for a file
src-programs/midi2melody.cpp.s:
	$(MAKE) -f CMakeFiles/midi2melody.dir/build.make CMakeFiles/midi2melody.dir/src-programs/midi2melody.cpp.s
.PHONY : src-programs/midi2melody.cpp.s

src-programs/midi2notes.o: src-programs/midi2notes.cpp.o

.PHONY : src-programs/midi2notes.o

# target to build an object file
src-programs/midi2notes.cpp.o:
	$(MAKE) -f CMakeFiles/midi2notes.dir/build.make CMakeFiles/midi2notes.dir/src-programs/midi2notes.cpp.o
.PHONY : src-programs/midi2notes.cpp.o

src-programs/midi2notes.i: src-programs/midi2notes.cpp.i

.PHONY : src-programs/midi2notes.i

# target to preprocess a source file
src-programs/midi2notes.cpp.i:
	$(MAKE) -f CMakeFiles/midi2notes.dir/build.make CMakeFiles/midi2notes.dir/src-programs/midi2notes.cpp.i
.PHONY : src-programs/midi2notes.cpp.i

src-programs/midi2notes.s: src-programs/midi2notes.cpp.s

.PHONY : src-programs/midi2notes.s

# target to generate assembly for a file
src-programs/midi2notes.cpp.s:
	$(MAKE) -f CMakeFiles/midi2notes.dir/build.make CMakeFiles/midi2notes.dir/src-programs/midi2notes.cpp.s
.PHONY : src-programs/midi2notes.cpp.s

src-programs/midi2skini.o: src-programs/midi2skini.cpp.o

.PHONY : src-programs/midi2skini.o

# target to build an object file
src-programs/midi2skini.cpp.o:
	$(MAKE) -f CMakeFiles/midi2skini.dir/build.make CMakeFiles/midi2skini.dir/src-programs/midi2skini.cpp.o
.PHONY : src-programs/midi2skini.cpp.o

src-programs/midi2skini.i: src-programs/midi2skini.cpp.i

.PHONY : src-programs/midi2skini.i

# target to preprocess a source file
src-programs/midi2skini.cpp.i:
	$(MAKE) -f CMakeFiles/midi2skini.dir/build.make CMakeFiles/midi2skini.dir/src-programs/midi2skini.cpp.i
.PHONY : src-programs/midi2skini.cpp.i

src-programs/midi2skini.s: src-programs/midi2skini.cpp.s

.PHONY : src-programs/midi2skini.s

# target to generate assembly for a file
src-programs/midi2skini.cpp.s:
	$(MAKE) -f CMakeFiles/midi2skini.dir/build.make CMakeFiles/midi2skini.dir/src-programs/midi2skini.cpp.s
.PHONY : src-programs/midi2skini.cpp.s

src-programs/midi2text.o: src-programs/midi2text.cpp.o

.PHONY : src-programs/midi2text.o

# target to build an object file
src-programs/midi2text.cpp.o:
	$(MAKE) -f CMakeFiles/midi2text.dir/build.make CMakeFiles/midi2text.dir/src-programs/midi2text.cpp.o
.PHONY : src-programs/midi2text.cpp.o

src-programs/midi2text.i: src-programs/midi2text.cpp.i

.PHONY : src-programs/midi2text.i

# target to preprocess a source file
src-programs/midi2text.cpp.i:
	$(MAKE) -f CMakeFiles/midi2text.dir/build.make CMakeFiles/midi2text.dir/src-programs/midi2text.cpp.i
.PHONY : src-programs/midi2text.cpp.i

src-programs/midi2text.s: src-programs/midi2text.cpp.s

.PHONY : src-programs/midi2text.s

# target to generate assembly for a file
src-programs/midi2text.cpp.s:
	$(MAKE) -f CMakeFiles/midi2text.dir/build.make CMakeFiles/midi2text.dir/src-programs/midi2text.cpp.s
.PHONY : src-programs/midi2text.cpp.s

src-programs/midicat.o: src-programs/midicat.cpp.o

.PHONY : src-programs/midicat.o

# target to build an object file
src-programs/midicat.cpp.o:
	$(MAKE) -f CMakeFiles/midicat.dir/build.make CMakeFiles/midicat.dir/src-programs/midicat.cpp.o
.PHONY : src-programs/midicat.cpp.o

src-programs/midicat.i: src-programs/midicat.cpp.i

.PHONY : src-programs/midicat.i

# target to preprocess a source file
src-programs/midicat.cpp.i:
	$(MAKE) -f CMakeFiles/midicat.dir/build.make CMakeFiles/midicat.dir/src-programs/midicat.cpp.i
.PHONY : src-programs/midicat.cpp.i

src-programs/midicat.s: src-programs/midicat.cpp.s

.PHONY : src-programs/midicat.s

# target to generate assembly for a file
src-programs/midicat.cpp.s:
	$(MAKE) -f CMakeFiles/midicat.dir/build.make CMakeFiles/midicat.dir/src-programs/midicat.cpp.s
.PHONY : src-programs/midicat.cpp.s

src-programs/midimixup.o: src-programs/midimixup.cpp.o

.PHONY : src-programs/midimixup.o

# target to build an object file
src-programs/midimixup.cpp.o:
	$(MAKE) -f CMakeFiles/midimixup.dir/build.make CMakeFiles/midimixup.dir/src-programs/midimixup.cpp.o
.PHONY : src-programs/midimixup.cpp.o

src-programs/midimixup.i: src-programs/midimixup.cpp.i

.PHONY : src-programs/midimixup.i

# target to preprocess a source file
src-programs/midimixup.cpp.i:
	$(MAKE) -f CMakeFiles/midimixup.dir/build.make CMakeFiles/midimixup.dir/src-programs/midimixup.cpp.i
.PHONY : src-programs/midimixup.cpp.i

src-programs/midimixup.s: src-programs/midimixup.cpp.s

.PHONY : src-programs/midimixup.s

# target to generate assembly for a file
src-programs/midimixup.cpp.s:
	$(MAKE) -f CMakeFiles/midimixup.dir/build.make CMakeFiles/midimixup.dir/src-programs/midimixup.cpp.s
.PHONY : src-programs/midimixup.cpp.s

src-programs/miditime.o: src-programs/miditime.cpp.o

.PHONY : src-programs/miditime.o

# target to build an object file
src-programs/miditime.cpp.o:
	$(MAKE) -f CMakeFiles/miditime.dir/build.make CMakeFiles/miditime.dir/src-programs/miditime.cpp.o
.PHONY : src-programs/miditime.cpp.o

src-programs/miditime.i: src-programs/miditime.cpp.i

.PHONY : src-programs/miditime.i

# target to preprocess a source file
src-programs/miditime.cpp.i:
	$(MAKE) -f CMakeFiles/miditime.dir/build.make CMakeFiles/miditime.dir/src-programs/miditime.cpp.i
.PHONY : src-programs/miditime.cpp.i

src-programs/miditime.s: src-programs/miditime.cpp.s

.PHONY : src-programs/miditime.s

# target to generate assembly for a file
src-programs/miditime.cpp.s:
	$(MAKE) -f CMakeFiles/miditime.dir/build.make CMakeFiles/miditime.dir/src-programs/miditime.cpp.s
.PHONY : src-programs/miditime.cpp.s

src-programs/perfid.o: src-programs/perfid.cpp.o

.PHONY : src-programs/perfid.o

# target to build an object file
src-programs/perfid.cpp.o:
	$(MAKE) -f CMakeFiles/perfid.dir/build.make CMakeFiles/perfid.dir/src-programs/perfid.cpp.o
.PHONY : src-programs/perfid.cpp.o

src-programs/perfid.i: src-programs/perfid.cpp.i

.PHONY : src-programs/perfid.i

# target to preprocess a source file
src-programs/perfid.cpp.i:
	$(MAKE) -f CMakeFiles/perfid.dir/build.make CMakeFiles/perfid.dir/src-programs/perfid.cpp.i
.PHONY : src-programs/perfid.cpp.i

src-programs/perfid.s: src-programs/perfid.cpp.s

.PHONY : src-programs/perfid.s

# target to generate assembly for a file
src-programs/perfid.cpp.s:
	$(MAKE) -f CMakeFiles/perfid.dir/build.make CMakeFiles/perfid.dir/src-programs/perfid.cpp.s
.PHONY : src-programs/perfid.cpp.s

src-programs/retick.o: src-programs/retick.cpp.o

.PHONY : src-programs/retick.o

# target to build an object file
src-programs/retick.cpp.o:
	$(MAKE) -f CMakeFiles/retick.dir/build.make CMakeFiles/retick.dir/src-programs/retick.cpp.o
.PHONY : src-programs/retick.cpp.o

src-programs/retick.i: src-programs/retick.cpp.i

.PHONY : src-programs/retick.i

# target to preprocess a source file
src-programs/retick.cpp.i:
	$(MAKE) -f CMakeFiles/retick.dir/build.make CMakeFiles/retick.dir/src-programs/retick.cpp.i
.PHONY : src-programs/retick.cpp.i

src-programs/retick.s: src-programs/retick.cpp.s

.PHONY : src-programs/retick.s

# target to generate assembly for a file
src-programs/retick.cpp.s:
	$(MAKE) -f CMakeFiles/retick.dir/build.make CMakeFiles/retick.dir/src-programs/retick.cpp.s
.PHONY : src-programs/retick.cpp.s

src-programs/shutak.o: src-programs/shutak.cpp.o

.PHONY : src-programs/shutak.o

# target to build an object file
src-programs/shutak.cpp.o:
	$(MAKE) -f CMakeFiles/shutak.dir/build.make CMakeFiles/shutak.dir/src-programs/shutak.cpp.o
.PHONY : src-programs/shutak.cpp.o

src-programs/shutak.i: src-programs/shutak.cpp.i

.PHONY : src-programs/shutak.i

# target to preprocess a source file
src-programs/shutak.cpp.i:
	$(MAKE) -f CMakeFiles/shutak.dir/build.make CMakeFiles/shutak.dir/src-programs/shutak.cpp.i
.PHONY : src-programs/shutak.cpp.i

src-programs/shutak.s: src-programs/shutak.cpp.s

.PHONY : src-programs/shutak.s

# target to generate assembly for a file
src-programs/shutak.cpp.s:
	$(MAKE) -f CMakeFiles/shutak.dir/build.make CMakeFiles/shutak.dir/src-programs/shutak.cpp.s
.PHONY : src-programs/shutak.cpp.s

src-programs/smfdur.o: src-programs/smfdur.cpp.o

.PHONY : src-programs/smfdur.o

# target to build an object file
src-programs/smfdur.cpp.o:
	$(MAKE) -f CMakeFiles/smfdur.dir/build.make CMakeFiles/smfdur.dir/src-programs/smfdur.cpp.o
.PHONY : src-programs/smfdur.cpp.o

src-programs/smfdur.i: src-programs/smfdur.cpp.i

.PHONY : src-programs/smfdur.i

# target to preprocess a source file
src-programs/smfdur.cpp.i:
	$(MAKE) -f CMakeFiles/smfdur.dir/build.make CMakeFiles/smfdur.dir/src-programs/smfdur.cpp.i
.PHONY : src-programs/smfdur.cpp.i

src-programs/smfdur.s: src-programs/smfdur.cpp.s

.PHONY : src-programs/smfdur.s

# target to generate assembly for a file
src-programs/smfdur.cpp.s:
	$(MAKE) -f CMakeFiles/smfdur.dir/build.make CMakeFiles/smfdur.dir/src-programs/smfdur.cpp.s
.PHONY : src-programs/smfdur.cpp.s

src-programs/stretch.o: src-programs/stretch.cpp.o

.PHONY : src-programs/stretch.o

# target to build an object file
src-programs/stretch.cpp.o:
	$(MAKE) -f CMakeFiles/stretch.dir/build.make CMakeFiles/stretch.dir/src-programs/stretch.cpp.o
.PHONY : src-programs/stretch.cpp.o

src-programs/stretch.i: src-programs/stretch.cpp.i

.PHONY : src-programs/stretch.i

# target to preprocess a source file
src-programs/stretch.cpp.i:
	$(MAKE) -f CMakeFiles/stretch.dir/build.make CMakeFiles/stretch.dir/src-programs/stretch.cpp.i
.PHONY : src-programs/stretch.cpp.i

src-programs/stretch.s: src-programs/stretch.cpp.s

.PHONY : src-programs/stretch.s

# target to generate assembly for a file
src-programs/stretch.cpp.s:
	$(MAKE) -f CMakeFiles/stretch.dir/build.make CMakeFiles/stretch.dir/src-programs/stretch.cpp.s
.PHONY : src-programs/stretch.cpp.s

src-programs/sysextest.o: src-programs/sysextest.cpp.o

.PHONY : src-programs/sysextest.o

# target to build an object file
src-programs/sysextest.cpp.o:
	$(MAKE) -f CMakeFiles/sysextest.dir/build.make CMakeFiles/sysextest.dir/src-programs/sysextest.cpp.o
.PHONY : src-programs/sysextest.cpp.o

src-programs/sysextest.i: src-programs/sysextest.cpp.i

.PHONY : src-programs/sysextest.i

# target to preprocess a source file
src-programs/sysextest.cpp.i:
	$(MAKE) -f CMakeFiles/sysextest.dir/build.make CMakeFiles/sysextest.dir/src-programs/sysextest.cpp.i
.PHONY : src-programs/sysextest.cpp.i

src-programs/sysextest.s: src-programs/sysextest.cpp.s

.PHONY : src-programs/sysextest.s

# target to generate assembly for a file
src-programs/sysextest.cpp.s:
	$(MAKE) -f CMakeFiles/sysextest.dir/build.make CMakeFiles/sysextest.dir/src-programs/sysextest.cpp.s
.PHONY : src-programs/sysextest.cpp.s

src-programs/text2midi.o: src-programs/text2midi.cpp.o

.PHONY : src-programs/text2midi.o

# target to build an object file
src-programs/text2midi.cpp.o:
	$(MAKE) -f CMakeFiles/text2midi.dir/build.make CMakeFiles/text2midi.dir/src-programs/text2midi.cpp.o
.PHONY : src-programs/text2midi.cpp.o

src-programs/text2midi.i: src-programs/text2midi.cpp.i

.PHONY : src-programs/text2midi.i

# target to preprocess a source file
src-programs/text2midi.cpp.i:
	$(MAKE) -f CMakeFiles/text2midi.dir/build.make CMakeFiles/text2midi.dir/src-programs/text2midi.cpp.i
.PHONY : src-programs/text2midi.cpp.i

src-programs/text2midi.s: src-programs/text2midi.cpp.s

.PHONY : src-programs/text2midi.s

# target to generate assembly for a file
src-programs/text2midi.cpp.s:
	$(MAKE) -f CMakeFiles/text2midi.dir/build.make CMakeFiles/text2midi.dir/src-programs/text2midi.cpp.s
.PHONY : src-programs/text2midi.cpp.s

src-programs/textmidi.o: src-programs/textmidi.cpp.o

.PHONY : src-programs/textmidi.o

# target to build an object file
src-programs/textmidi.cpp.o:
	$(MAKE) -f CMakeFiles/textmidi.dir/build.make CMakeFiles/textmidi.dir/src-programs/textmidi.cpp.o
.PHONY : src-programs/textmidi.cpp.o

src-programs/textmidi.i: src-programs/textmidi.cpp.i

.PHONY : src-programs/textmidi.i

# target to preprocess a source file
src-programs/textmidi.cpp.i:
	$(MAKE) -f CMakeFiles/textmidi.dir/build.make CMakeFiles/textmidi.dir/src-programs/textmidi.cpp.i
.PHONY : src-programs/textmidi.cpp.i

src-programs/textmidi.s: src-programs/textmidi.cpp.s

.PHONY : src-programs/textmidi.s

# target to generate assembly for a file
src-programs/textmidi.cpp.s:
	$(MAKE) -f CMakeFiles/textmidi.dir/build.make CMakeFiles/textmidi.dir/src-programs/textmidi.cpp.s
.PHONY : src-programs/textmidi.cpp.s

src-programs/toascii.o: src-programs/toascii.cpp.o

.PHONY : src-programs/toascii.o

# target to build an object file
src-programs/toascii.cpp.o:
	$(MAKE) -f CMakeFiles/toascii.dir/build.make CMakeFiles/toascii.dir/src-programs/toascii.cpp.o
.PHONY : src-programs/toascii.cpp.o

src-programs/toascii.i: src-programs/toascii.cpp.i

.PHONY : src-programs/toascii.i

# target to preprocess a source file
src-programs/toascii.cpp.i:
	$(MAKE) -f CMakeFiles/toascii.dir/build.make CMakeFiles/toascii.dir/src-programs/toascii.cpp.i
.PHONY : src-programs/toascii.cpp.i

src-programs/toascii.s: src-programs/toascii.cpp.s

.PHONY : src-programs/toascii.s

# target to generate assembly for a file
src-programs/toascii.cpp.s:
	$(MAKE) -f CMakeFiles/toascii.dir/build.make CMakeFiles/toascii.dir/src-programs/toascii.cpp.s
.PHONY : src-programs/toascii.cpp.s

src-programs/tobin.o: src-programs/tobin.cpp.o

.PHONY : src-programs/tobin.o

# target to build an object file
src-programs/tobin.cpp.o:
	$(MAKE) -f CMakeFiles/tobin.dir/build.make CMakeFiles/tobin.dir/src-programs/tobin.cpp.o
.PHONY : src-programs/tobin.cpp.o

src-programs/tobin.i: src-programs/tobin.cpp.i

.PHONY : src-programs/tobin.i

# target to preprocess a source file
src-programs/tobin.cpp.i:
	$(MAKE) -f CMakeFiles/tobin.dir/build.make CMakeFiles/tobin.dir/src-programs/tobin.cpp.i
.PHONY : src-programs/tobin.cpp.i

src-programs/tobin.s: src-programs/tobin.cpp.s

.PHONY : src-programs/tobin.s

# target to generate assembly for a file
src-programs/tobin.cpp.s:
	$(MAKE) -f CMakeFiles/tobin.dir/build.make CMakeFiles/tobin.dir/src-programs/tobin.cpp.s
.PHONY : src-programs/tobin.cpp.s

src-programs/tobinary.o: src-programs/tobinary.cpp.o

.PHONY : src-programs/tobinary.o

# target to build an object file
src-programs/tobinary.cpp.o:
	$(MAKE) -f CMakeFiles/tobinary.dir/build.make CMakeFiles/tobinary.dir/src-programs/tobinary.cpp.o
.PHONY : src-programs/tobinary.cpp.o

src-programs/tobinary.i: src-programs/tobinary.cpp.i

.PHONY : src-programs/tobinary.i

# target to preprocess a source file
src-programs/tobinary.cpp.i:
	$(MAKE) -f CMakeFiles/tobinary.dir/build.make CMakeFiles/tobinary.dir/src-programs/tobinary.cpp.i
.PHONY : src-programs/tobinary.cpp.i

src-programs/tobinary.s: src-programs/tobinary.cpp.s

.PHONY : src-programs/tobinary.s

# target to generate assembly for a file
src-programs/tobinary.cpp.s:
	$(MAKE) -f CMakeFiles/tobinary.dir/build.make CMakeFiles/tobinary.dir/src-programs/tobinary.cpp.s
.PHONY : src-programs/tobinary.cpp.s

src-programs/todec.o: src-programs/todec.cpp.o

.PHONY : src-programs/todec.o

# target to build an object file
src-programs/todec.cpp.o:
	$(MAKE) -f CMakeFiles/todec.dir/build.make CMakeFiles/todec.dir/src-programs/todec.cpp.o
.PHONY : src-programs/todec.cpp.o

src-programs/todec.i: src-programs/todec.cpp.i

.PHONY : src-programs/todec.i

# target to preprocess a source file
src-programs/todec.cpp.i:
	$(MAKE) -f CMakeFiles/todec.dir/build.make CMakeFiles/todec.dir/src-programs/todec.cpp.i
.PHONY : src-programs/todec.cpp.i

src-programs/todec.s: src-programs/todec.cpp.s

.PHONY : src-programs/todec.s

# target to generate assembly for a file
src-programs/todec.cpp.s:
	$(MAKE) -f CMakeFiles/todec.dir/build.make CMakeFiles/todec.dir/src-programs/todec.cpp.s
.PHONY : src-programs/todec.cpp.s

src-programs/tohex.o: src-programs/tohex.cpp.o

.PHONY : src-programs/tohex.o

# target to build an object file
src-programs/tohex.cpp.o:
	$(MAKE) -f CMakeFiles/tohex.dir/build.make CMakeFiles/tohex.dir/src-programs/tohex.cpp.o
.PHONY : src-programs/tohex.cpp.o

src-programs/tohex.i: src-programs/tohex.cpp.i

.PHONY : src-programs/tohex.i

# target to preprocess a source file
src-programs/tohex.cpp.i:
	$(MAKE) -f CMakeFiles/tohex.dir/build.make CMakeFiles/tohex.dir/src-programs/tohex.cpp.i
.PHONY : src-programs/tohex.cpp.i

src-programs/tohex.s: src-programs/tohex.cpp.s

.PHONY : src-programs/tohex.s

# target to generate assembly for a file
src-programs/tohex.cpp.s:
	$(MAKE) -f CMakeFiles/tohex.dir/build.make CMakeFiles/tohex.dir/src-programs/tohex.cpp.s
.PHONY : src-programs/tohex.cpp.s

src-programs/type0.o: src-programs/type0.cpp.o

.PHONY : src-programs/type0.o

# target to build an object file
src-programs/type0.cpp.o:
	$(MAKE) -f CMakeFiles/type0.dir/build.make CMakeFiles/type0.dir/src-programs/type0.cpp.o
.PHONY : src-programs/type0.cpp.o

src-programs/type0.i: src-programs/type0.cpp.i

.PHONY : src-programs/type0.i

# target to preprocess a source file
src-programs/type0.cpp.i:
	$(MAKE) -f CMakeFiles/type0.dir/build.make CMakeFiles/type0.dir/src-programs/type0.cpp.i
.PHONY : src-programs/type0.cpp.i

src-programs/type0.s: src-programs/type0.cpp.s

.PHONY : src-programs/type0.s

# target to generate assembly for a file
src-programs/type0.cpp.s:
	$(MAKE) -f CMakeFiles/type0.dir/build.make CMakeFiles/type0.dir/src-programs/type0.cpp.s
.PHONY : src-programs/type0.cpp.s

src-programs/vlv.o: src-programs/vlv.cpp.o

.PHONY : src-programs/vlv.o

# target to build an object file
src-programs/vlv.cpp.o:
	$(MAKE) -f CMakeFiles/vlv.dir/build.make CMakeFiles/vlv.dir/src-programs/vlv.cpp.o
.PHONY : src-programs/vlv.cpp.o

src-programs/vlv.i: src-programs/vlv.cpp.i

.PHONY : src-programs/vlv.i

# target to preprocess a source file
src-programs/vlv.cpp.i:
	$(MAKE) -f CMakeFiles/vlv.dir/build.make CMakeFiles/vlv.dir/src-programs/vlv.cpp.i
.PHONY : src-programs/vlv.cpp.i

src-programs/vlv.s: src-programs/vlv.cpp.s

.PHONY : src-programs/vlv.s

# target to generate assembly for a file
src-programs/vlv.cpp.s:
	$(MAKE) -f CMakeFiles/vlv.dir/build.make CMakeFiles/vlv.dir/src-programs/vlv.cpp.s
.PHONY : src-programs/vlv.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... midi2text"
	@echo "... midi2notes"
	@echo "... midifile"
	@echo "... tobinary"
	@echo "... tohex"
	@echo "... midi2melody"
	@echo "... midi2binasc"
	@echo "... mid2mat"
	@echo "... retick"
	@echo "... durations"
	@echo "... createmidifile2"
	@echo "... textmidi"
	@echo "... mid2svg"
	@echo "... mid2mtb"
	@echo "... midi2skini"
	@echo "... drumtab"
	@echo "... asciimidi"
	@echo "... binasc"
	@echo "... createmidifile"
	@echo "... midicat"
	@echo "... fyp"
	@echo "... midimixup"
	@echo "... miditime"
	@echo "... sysextest"
	@echo "... todec"
	@echo "... midi2beep"
	@echo "... perfid"
	@echo "... toascii"
	@echo "... type0"
	@echo "... shutak"
	@echo "... 80off"
	@echo "... text2midi"
	@echo "... smfdur"
	@echo "... stretch"
	@echo "... tobin"
	@echo "... vlv"
	@echo "... src-library/Binasc.o"
	@echo "... src-library/Binasc.i"
	@echo "... src-library/Binasc.s"
	@echo "... src-library/MidiCat.o"
	@echo "... src-library/MidiCat.i"
	@echo "... src-library/MidiCat.s"
	@echo "... src-library/MidiEvent.o"
	@echo "... src-library/MidiEvent.i"
	@echo "... src-library/MidiEvent.s"
	@echo "... src-library/MidiEventList.o"
	@echo "... src-library/MidiEventList.i"
	@echo "... src-library/MidiEventList.s"
	@echo "... src-library/MidiExcerptByBar.o"
	@echo "... src-library/MidiExcerptByBar.i"
	@echo "... src-library/MidiExcerptByBar.s"
	@echo "... src-library/MidiFile.o"
	@echo "... src-library/MidiFile.i"
	@echo "... src-library/MidiFile.s"
	@echo "... src-library/MidiMessage.o"
	@echo "... src-library/MidiMessage.i"
	@echo "... src-library/MidiMessage.s"
	@echo "... src-library/MusicSegment.o"
	@echo "... src-library/MusicSegment.i"
	@echo "... src-library/MusicSegment.s"
	@echo "... src-library/Options.o"
	@echo "... src-library/Options.i"
	@echo "... src-library/Options.s"
	@echo "... src-programs/80off.o"
	@echo "... src-programs/80off.i"
	@echo "... src-programs/80off.s"
	@echo "... src-programs/asciimidi.o"
	@echo "... src-programs/asciimidi.i"
	@echo "... src-programs/asciimidi.s"
	@echo "... src-programs/binasc.o"
	@echo "... src-programs/binasc.i"
	@echo "... src-programs/binasc.s"
	@echo "... src-programs/createmidifile.o"
	@echo "... src-programs/createmidifile.i"
	@echo "... src-programs/createmidifile.s"
	@echo "... src-programs/createmidifile2.o"
	@echo "... src-programs/createmidifile2.i"
	@echo "... src-programs/createmidifile2.s"
	@echo "... src-programs/drumtab.o"
	@echo "... src-programs/drumtab.i"
	@echo "... src-programs/drumtab.s"
	@echo "... src-programs/durations.o"
	@echo "... src-programs/durations.i"
	@echo "... src-programs/durations.s"
	@echo "... src-programs/fyp.o"
	@echo "... src-programs/fyp.i"
	@echo "... src-programs/fyp.s"
	@echo "... src-programs/mid2mat.o"
	@echo "... src-programs/mid2mat.i"
	@echo "... src-programs/mid2mat.s"
	@echo "... src-programs/mid2mtb.o"
	@echo "... src-programs/mid2mtb.i"
	@echo "... src-programs/mid2mtb.s"
	@echo "... src-programs/mid2svg.o"
	@echo "... src-programs/mid2svg.i"
	@echo "... src-programs/mid2svg.s"
	@echo "... src-programs/midi2beep.o"
	@echo "... src-programs/midi2beep.i"
	@echo "... src-programs/midi2beep.s"
	@echo "... src-programs/midi2binasc.o"
	@echo "... src-programs/midi2binasc.i"
	@echo "... src-programs/midi2binasc.s"
	@echo "... src-programs/midi2melody.o"
	@echo "... src-programs/midi2melody.i"
	@echo "... src-programs/midi2melody.s"
	@echo "... src-programs/midi2notes.o"
	@echo "... src-programs/midi2notes.i"
	@echo "... src-programs/midi2notes.s"
	@echo "... src-programs/midi2skini.o"
	@echo "... src-programs/midi2skini.i"
	@echo "... src-programs/midi2skini.s"
	@echo "... src-programs/midi2text.o"
	@echo "... src-programs/midi2text.i"
	@echo "... src-programs/midi2text.s"
	@echo "... src-programs/midicat.o"
	@echo "... src-programs/midicat.i"
	@echo "... src-programs/midicat.s"
	@echo "... src-programs/midimixup.o"
	@echo "... src-programs/midimixup.i"
	@echo "... src-programs/midimixup.s"
	@echo "... src-programs/miditime.o"
	@echo "... src-programs/miditime.i"
	@echo "... src-programs/miditime.s"
	@echo "... src-programs/perfid.o"
	@echo "... src-programs/perfid.i"
	@echo "... src-programs/perfid.s"
	@echo "... src-programs/retick.o"
	@echo "... src-programs/retick.i"
	@echo "... src-programs/retick.s"
	@echo "... src-programs/shutak.o"
	@echo "... src-programs/shutak.i"
	@echo "... src-programs/shutak.s"
	@echo "... src-programs/smfdur.o"
	@echo "... src-programs/smfdur.i"
	@echo "... src-programs/smfdur.s"
	@echo "... src-programs/stretch.o"
	@echo "... src-programs/stretch.i"
	@echo "... src-programs/stretch.s"
	@echo "... src-programs/sysextest.o"
	@echo "... src-programs/sysextest.i"
	@echo "... src-programs/sysextest.s"
	@echo "... src-programs/text2midi.o"
	@echo "... src-programs/text2midi.i"
	@echo "... src-programs/text2midi.s"
	@echo "... src-programs/textmidi.o"
	@echo "... src-programs/textmidi.i"
	@echo "... src-programs/textmidi.s"
	@echo "... src-programs/toascii.o"
	@echo "... src-programs/toascii.i"
	@echo "... src-programs/toascii.s"
	@echo "... src-programs/tobin.o"
	@echo "... src-programs/tobin.i"
	@echo "... src-programs/tobin.s"
	@echo "... src-programs/tobinary.o"
	@echo "... src-programs/tobinary.i"
	@echo "... src-programs/tobinary.s"
	@echo "... src-programs/todec.o"
	@echo "... src-programs/todec.i"
	@echo "... src-programs/todec.s"
	@echo "... src-programs/tohex.o"
	@echo "... src-programs/tohex.i"
	@echo "... src-programs/tohex.s"
	@echo "... src-programs/type0.o"
	@echo "... src-programs/type0.i"
	@echo "... src-programs/type0.s"
	@echo "... src-programs/vlv.o"
	@echo "... src-programs/vlv.i"
	@echo "... src-programs/vlv.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

